baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imustafin.tatar" # the base hostname & protocol for your site, e.g. http://example.com
title: imustafin.tatar
social:
  links:
    - https://github.com/imustafin
    - https://www.linkedin.com/in/ilgiz-mustafin-288b99178

# Render posts with time in the future
future: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from
  - jekyll-plantuml
  - jekyll-inline-svg
  - jekyll-tailwindcss

svg:
  optimize: true

postcss:
  cache: false

redirect_from:
  json: false

liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

breadcrumbs:
  root:
    hide: false
    image: false

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - favicon/
  - tailwind.config.js
  - postcss.config.js
  - dev.sh
  - test/
  - Rakefile
  - assets/fonts/roboto-slab/LICENSE.txt
  - assets/fonts/roboto-slab/README.txt

defaults:
  - scope:
      path: ""
    values:
      crumbtitle: false
      no_json_ld: true
      last_modified_at: false
      include_in_sitemap: true
      redirect: false
      schema_type: WebPage
      author:
        name: Ilgiz Mustafin
        url: https://imustafin.tatar/
  - scope:
      path: ''
    values:
      lang: en
  - scope:
      path: ''
      type: posts
    values:
      permalink: /blog/:title
  - scope:
      path: '_posts/projects'
      type: posts
    values: &project_defaults
      is_project: true
      permalink: /projects/:title
  - scope:
      path: ru
    values:
      lang: ru
      author:
        name: Ильгиз Мустафин
        url: https://imustafin.tatar/
  - scope:
      path: ru
      type: posts
    values:
      permalink: /ru/%D0%B1%D0%BB%D0%BE%D0%B3/:title
  - scope:
      path: 'ru/_posts/проекты'
      type: posts
    values:
      <<: *project_defaults
      permalink: /ru/%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B/:title
  - scope:
      path: tt
    values:
      lang: tt
      author:
        name: Ильгиз Мустафин
        url: https://imustafin.tatar/
  - scope:
      path: tt
      type: posts
    values:
      permalink: /tt/%D0%B1%D0%BB%D0%BE%D0%B3/:title
  - scope:
      path: 'tt/_posts/проектлар'
      type: posts
    values:
      <<: *project_defaults
      permalink: /tt/%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%BB%D0%B0%D1%80/:title
