baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imustafin.tatar" # the base hostname & protocol for your site, e.g. http://example.com
show_downloads: false
title: imustafin.tatar
social:
  links:
    - https://github.com/imustafin
    - https://www.linkedin.com/in/ilgiz-mustafin-288b99178

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jemoji

liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

permalink: none

defaults:
  - scope:
      path: ""
    values:
      last_modified_at: false
      include_in_sitemap: true
  - scope:
      path: en
    values:
      lang: en
  - scope:
      path: ru
    values:
      lang: ru
  - scope:
      path: tt
    values:
      lang: tt
  - scope:
      path: en/dictionary/word
    values: &dictionary
      in_dictionary: true
      layout: dictionary_word
      translation-sources: null
      translation-etymology: null
  - scope:
      path: ru/словарь/слово
    values:
      <<: *dictionary
  - scope:
      path: tt/сүзлек/сүз
    values:
      <<: *dictionary
