baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imustafin.tatar" # the base hostname & protocol for your site, e.g. http://example.com
show_downloads: false
title: imustafin.tatar
social:
  links:
    - https://github.com/imustafin
    - https://www.linkedin.com/in/ilgiz-mustafin-288b99178

# Build settings
markdown: kramdown
# theme: jekyll-theme-cayman
plugins:
  - jemoji
  - jekyll-remote-theme
  - jekyll-redirect-from

redirect_from:
  json: false

remote_theme: pages-themes/cayman

liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

breadcrumbs:
  root:
    hide: true
    image: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - favicon/

defaults:
  - scope:
      path: ""
    values:
      last_modified_at: false
      include_in_sitemap: true
      redirect: false
      author:
        name: Ilgiz Mustafin
  - scope:
      path: en
    values:
      lang: en
  - scope:
      path: en
      type: posts
    values:
      permalink: /en/blog/:title
  - scope:
      path: ru
    values:
      lang: ru
      author:
        name: Ильгиз Мустафин
  - scope:
      path: ru
      type: posts
    values:
      permalink: /ru/%D0%B1%D0%BB%D0%BE%D0%B3/:title
  - scope:
      path: tt
    values:
      lang: tt
      author:
        name: Ильгиз Мустафин
  - scope:
      path: tt
      type: posts
    values:
      permalink: /tt/%D0%B1%D0%BB%D0%BE%D0%B3/:title
  - scope:
      path: en/dictionary/word
    values: &dictionary
      in_dictionary: true
      layout: dictionary_word
      translation-sources: null
      translation-etymology: null
  - scope:
      path: ru/словарь/слово
    values:
      <<: *dictionary
  - scope:
      path: tt/сүзлек/сүз
    values:
      <<: *dictionary
