name: Build to gh-pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          format_output: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
