name: Test build

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: Install PlantUML and libvips
        run: |
          sudo apt-get update -y
          sudo apt-get install -y plantuml libvips
          wget https://sourceforge.net/projects/plantuml/files/1.2021.12/plantuml.1.2021.12.jar/download -O plantuml.jar
          sudo mv plantuml.jar /usr/share/plantuml/plantuml.jar

      - name: Build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          format_output: true

      - name: Run tests
        run: bundle exec rake test
