name: Test build

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install PlantUML and libvips
        env:
          PLANTUML_JAR: https://github.com/plantuml/plantuml/releases/download/v1.2023.13/plantuml-1.2023.13.jar
        run: |
          sudo apt-get update -y
          sudo apt-get install -y plantuml libvips
          wget $PLANTUML_JAR -O plantuml.jar
          sudo mv plantuml.jar /usr/share/plantuml/plantuml.jar

      - name: Build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          format_output: true

      - name: Run tests
        run: bundle exec rake test
